#ifndef XPARAMETERS_H   /* prevent circular inclusions */
#define XPARAMETERS_H   /* by using protection macros */

#define XPAR_XGPIO_NUM_INSTANCES 4

/* Definitions for peripheral AXI_GPIO_0 */
#define XPAR_AXI_GPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_0_BASEADDR 0x40000000
#define XPAR_AXI_GPIO_0_HIGHADDR 0x4000ffff
#define XPAR_AXI_GPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_0_IS_DUAL 0x1
#define XPAR_AXI_GPIO_0_INTERRUPTS 0x2004
#define XPAR_FABRIC_AXI_GPIO_0_INTR 4
#define XPAR_AXI_GPIO_0_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_0_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_0 */
#define XPAR_XGPIO_0_BASEADDR 0x40000000
#define XPAR_FABRIC_XGPIO_0_INTR 4
#define XPAR_XGPIO_0_HIGHADDR 0x4000ffff
#define XPAR_XGPIO_0_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_0_GPIO_WIDTH 0x8
#define XPAR_XGPIO_0_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_0_IS_DUAL 0x1
#define XPAR_XGPIO_0_INTERRUPTS 0x2004
#define XPAR_XGPIO_0_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_1 */
#define XPAR_AXI_GPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_1_BASEADDR 0x40010000
#define XPAR_AXI_GPIO_1_HIGHADDR 0x4001ffff
#define XPAR_AXI_GPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_AXI_GPIO_1_IS_DUAL 0x1
#define XPAR_AXI_GPIO_1_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_1 */
#define XPAR_XGPIO_1_BASEADDR 0x40010000
#define XPAR_XGPIO_1_HIGHADDR 0x4001ffff
#define XPAR_XGPIO_1_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_1_GPIO_WIDTH 0x8
#define XPAR_XGPIO_1_INTERRUPT_PRESENT 0x0
#define XPAR_XGPIO_1_IS_DUAL 0x1

/* Definitions for peripheral AXI_GPIO_2 */
#define XPAR_AXI_GPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_2_BASEADDR 0x40020000
#define XPAR_AXI_GPIO_2_HIGHADDR 0x4002ffff
#define XPAR_AXI_GPIO_2_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_2_IS_DUAL 0x1
#define XPAR_AXI_GPIO_2_INTERRUPTS 0x2003
#define XPAR_FABRIC_AXI_GPIO_2_INTR 3
#define XPAR_AXI_GPIO_2_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_2_GPIO_WIDTH 0x8

/* Canonical definitions for peripheral AXI_GPIO_2 */
#define XPAR_XGPIO_2_BASEADDR 0x40020000
#define XPAR_FABRIC_XGPIO_2_INTR 3
#define XPAR_XGPIO_2_HIGHADDR 0x4002ffff
#define XPAR_XGPIO_2_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_2_GPIO_WIDTH 0x8
#define XPAR_XGPIO_2_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_2_IS_DUAL 0x1
#define XPAR_XGPIO_2_INTERRUPTS 0x2003
#define XPAR_XGPIO_2_INTERRUPT_PARENT 0x41200001

/* Definitions for peripheral AXI_GPIO_3 */
#define XPAR_AXI_GPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_AXI_GPIO_3_BASEADDR 0x40030000
#define XPAR_AXI_GPIO_3_HIGHADDR 0x4003ffff
#define XPAR_AXI_GPIO_3_INTERRUPT_PRESENT 0x1
#define XPAR_AXI_GPIO_3_IS_DUAL 0x1
#define XPAR_AXI_GPIO_3_INTERRUPTS 0x2002
#define XPAR_FABRIC_AXI_GPIO_3_INTR 2
#define XPAR_AXI_GPIO_3_INTERRUPT_PARENT 0x41200001
#define XPAR_AXI_GPIO_3_GPIO_WIDTH 0x4

/* Canonical definitions for peripheral AXI_GPIO_3 */
#define XPAR_XGPIO_3_BASEADDR 0x40030000
#define XPAR_FABRIC_XGPIO_3_INTR 2
#define XPAR_XGPIO_3_HIGHADDR 0x4003ffff
#define XPAR_XGPIO_3_COMPATIBLE "xlnx,axi-gpio-2.0"
#define XPAR_XGPIO_3_GPIO_WIDTH 0x4
#define XPAR_XGPIO_3_INTERRUPT_PRESENT 0x1
#define XPAR_XGPIO_3_IS_DUAL 0x1
#define XPAR_XGPIO_3_INTERRUPTS 0x2002
#define XPAR_XGPIO_3_INTERRUPT_PARENT 0x41200001

#define XPAR_XINTC_NUM_INSTANCES 1

/* Definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_MICROBLAZE_0_AXI_INTC_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_MICROBLAZE_0_AXI_INTC_BASEADDR 0x41200000
#define XPAR_MICROBLAZE_0_AXI_INTC_HIGHADDR 0x4120ffff
#define XPAR_MICROBLAZE_0_AXI_INTC_KIND_OF_INTR 0x23
#define XPAR_MICROBLAZE_0_AXI_INTC_IS_FAST 0x1
#define XPAR_MICROBLAZE_0_AXI_INTC_IVAR_RST_VAL 0x10
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_INTR_INPUTS 0x6
#define XPAR_MICROBLAZE_0_AXI_INTC_ADDR_WIDTH 0x20
#define XPAR_MICROBLAZE_0_AXI_INTC_OPTIONS 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_INTCTYPE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_HANDLER_TABLE 0x0
#define XPAR_MICROBLAZE_0_AXI_INTC_NUM_SW_INTR 0x0

/* Canonical definitions for peripheral MICROBLAZE_0_AXI_INTC */
#define XPAR_XINTC_0_BASEADDR 0x41200000
#define XPAR_XINTC_0_HIGHADDR 0x4120ffff
#define XPAR_XINTC_0_HANDLER_TABLE 0x0
#define XPAR_XINTC_0_ADDR_WIDTH 0x20
#define XPAR_XINTC_0_COMPATIBLE "xlnx,axi-intc-4.1"
#define XPAR_XINTC_0_IS_FAST 0x1
#define XPAR_XINTC_0_IVAR_RST_VAL 0x10
#define XPAR_XINTC_0_INTCTYPE 0x0
#define XPAR_XINTC_0_KIND_OF_INTR 0x23
#define XPAR_XINTC_0_NUM_INTR_INPUTS 0x6
#define XPAR_XINTC_0_NUM_SW_INTR 0x0
#define XPAR_XINTC_0_OPTIONS 0x0

#define XPAR_XSPI_NUM_INSTANCES 2

/* Definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_AXI_QUAD_SPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_0_BASEADDR 0x44a00000
#define XPAR_AXI_QUAD_SPI_0_HIGHADDR 0x44a0ffff
#define XPAR_AXI_QUAD_SPI_0_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_0_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_0_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_0_BITS_PER_WORD 0x10
#define XPAR_AXI_QUAD_SPI_0_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_0_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_0_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_0_STARTUP_BLOCK 0x0
#define XPAR_AXI_QUAD_SPI_0_FIFO_SIZE 0x10
#define XPAR_AXI_QUAD_SPI_0_INTERRUPTS 0x1
#define XPAR_FABRIC_AXI_QUAD_SPI_0_INTR 1
#define XPAR_AXI_QUAD_SPI_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_0 */
#define XPAR_XSPI_0_AXI4_ADDRESS 0x0
#define XPAR_XSPI_0_BASEADDR 0x44a00000
#define XPAR_FABRIC_XSPI_0_INTR 1
#define XPAR_XSPI_0_HIGHADDR 0x44a0ffff
#define XPAR_XSPI_0_AXI_INTERFACE 0x0
#define XPAR_XSPI_0_BITS_PER_WORD 0x10
#define XPAR_XSPI_0_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_0_FIFO_SIZE 0x10
#define XPAR_XSPI_0_HASFIFOS 0x1
#define XPAR_XSPI_0_INTERRUPTS 0x1
#define XPAR_XSPI_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_0_NUM_SS_BITS 0x1
#define XPAR_XSPI_0_SLAVEONLY 0x0
#define XPAR_XSPI_0_SPI_MODE 0x0
#define XPAR_XSPI_0_STARTUP_BLOCK 0x0
#define XPAR_XSPI_0_XIP_MODE 0x0

/* Definitions for peripheral AXI_QUAD_SPI_1 */
#define XPAR_AXI_QUAD_SPI_1_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_AXI_QUAD_SPI_1_BASEADDR 0x44a10000
#define XPAR_AXI_QUAD_SPI_1_HIGHADDR 0x44a1ffff
#define XPAR_AXI_QUAD_SPI_1_HASFIFOS 0x1
#define XPAR_AXI_QUAD_SPI_1_SLAVEONLY 0x0
#define XPAR_AXI_QUAD_SPI_1_NUM_SS_BITS 0x1
#define XPAR_AXI_QUAD_SPI_1_BITS_PER_WORD 0x10
#define XPAR_AXI_QUAD_SPI_1_SPI_MODE 0x0
#define XPAR_AXI_QUAD_SPI_1_AXI_INTERFACE 0x0
#define XPAR_AXI_QUAD_SPI_1_AXI4_ADDRESS 0x0
#define XPAR_AXI_QUAD_SPI_1_XIP_MODE 0x0
#define XPAR_AXI_QUAD_SPI_1_STARTUP_BLOCK 0x0
#define XPAR_AXI_QUAD_SPI_1_FIFO_SIZE 0x10
#define XPAR_AXI_QUAD_SPI_1_INTERRUPTS 0x0
#define XPAR_FABRIC_AXI_QUAD_SPI_1_INTR 0
#define XPAR_AXI_QUAD_SPI_1_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_QUAD_SPI_1 */
#define XPAR_XSPI_1_AXI4_ADDRESS 0x0
#define XPAR_XSPI_1_BASEADDR 0x44a10000
#define XPAR_FABRIC_XSPI_1_INTR 0
#define XPAR_XSPI_1_HIGHADDR 0x44a1ffff
#define XPAR_XSPI_1_AXI_INTERFACE 0x0
#define XPAR_XSPI_1_BITS_PER_WORD 0x10
#define XPAR_XSPI_1_COMPATIBLE "xlnx,axi-quad-spi-3.2"
#define XPAR_XSPI_1_FIFO_SIZE 0x10
#define XPAR_XSPI_1_HASFIFOS 0x1
#define XPAR_XSPI_1_INTERRUPTS 0x0
#define XPAR_XSPI_1_INTERRUPT_PARENT 0x41200001
#define XPAR_XSPI_1_NUM_SS_BITS 0x1
#define XPAR_XSPI_1_SLAVEONLY 0x0
#define XPAR_XSPI_1_SPI_MODE 0x0
#define XPAR_XSPI_1_STARTUP_BLOCK 0x0
#define XPAR_XSPI_1_XIP_MODE 0x0

#define XPAR_XUARTLITE_NUM_INSTANCES 1

/* Definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_AXI_UARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_AXI_UARTLITE_0_BASEADDR 0x40600000
#define XPAR_AXI_UARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_AXI_UARTLITE_0_BAUDRATE 0x1c200
#define XPAR_AXI_UARTLITE_0_USE_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_ODD_PARITY 0x0
#define XPAR_AXI_UARTLITE_0_DATA_BITS 0x8
#define XPAR_AXI_UARTLITE_0_INTERRUPTS 0x5
#define XPAR_FABRIC_AXI_UARTLITE_0_INTR 5
#define XPAR_AXI_UARTLITE_0_INTERRUPT_PARENT 0x41200001

/* Canonical definitions for peripheral AXI_UARTLITE_0 */
#define XPAR_XUARTLITE_0_BASEADDR 0x40600000
#define XPAR_FABRIC_XUARTLITE_0_INTR 5
#define XPAR_XUARTLITE_0_HIGHADDR 0x4060ffff
#define XPAR_XUARTLITE_0_BAUDRATE 0x1c200
#define XPAR_XUARTLITE_0_COMPATIBLE "xlnx,axi-uartlite-2.0"
#define XPAR_XUARTLITE_0_DATA_BITS 0x8
#define XPAR_XUARTLITE_0_INTERRUPTS 0x5
#define XPAR_XUARTLITE_0_INTERRUPT_PARENT 0x41200001
#define XPAR_XUARTLITE_0_ODD_PARITY 0x0
#define XPAR_XUARTLITE_0_USE_PARITY 0x0

#define XPAR_LMB_BRAM_0_BASEADDRESS 0x0
#define XPAR_LMB_BRAM_0_HIGHADDRESS 0x7fff
#define XPAR_CPU_CORE_CLOCK_FREQ_HZ 100000000

#define XPAR_MICROBLAZE_ADDR_SIZE 32

#define XPAR_MICROBLAZE_USE_STACK_PROTECTION 0

/* Number of SLRs */
#define NUMBER_OF_SLRS 0x1

/* Device ID */
#define XPAR_DEVICE_ID "7z020"

#endif  /* end of protection macro */